#This script will use rotated component scores from a PCA to create a similarity matrix
#Interpreting this matrix as a weighted adjacency matrix, the script proceeds to create a backbone network using Foti et al's (2011) LANS algorithm. 
#If you use code from this script, please cite:
#Authors (2019). Double network-based method for identifying behavioral patterns in clickstream data. MethodX. DOI: XXX

#First load clickstreamClusterMethodSession.r
#Then load clickstreamClusterMethodSessionNetworks.r
#######MAKING SIMILARITY NETWORK#############
Mat<-as.matrix(pca.net$scores) #Each sessions scores on each component
distMat<-dist(Mat,method="euclidean") #A distance matrix in component space. 
distMat<-as.matrix(distMat)
adjMat<-exp(-distMat) #An exponential transformation of distances to produce similarities between 0 (d=inf) and 1 (d=0). 

source("backboneExtraction.r") #If you use this script, please cite Author 2019

g<-graph_from_adjacency_matrix(adjMat[ps,ps],weighted=T,diag=F,mode = "upper") #Make a subnetwork of the problem-solving sessions
V(g)$id<-V(g)$name 
gBB<-backboneNetwork(g,0.05,2) #Create the backbone network with alpha=0.05
write_graph(gBB,"backbone.net",format="pajek") #Write the backbone network to working directory. 

#######FINDING CLUSTERS######################

#To find overlapping clusters, use Infomap. 
#Go to mapequation.org and follow the instructions there
#Once installed, run through infomap with the following code:
#./Infomap backbone.net --overlapping [outputfolder]
#Retrieve .tree file and extract clusters
#Or use this:
overlap<-read.csv("overlappingGroups.csv",dec = ",")

#We create a matrix to keep account of each session's membership
memMat<-matrix(0,ncol=12,nrow=231)
for (i in 1:length(overlap[,1])){
  memMat[overlap$node[i],overlap$group[i]]<-overlap$flow[i]#for each node for each cluster, list the flow as calculated by Infomap
}
memMat<-memMat/rowSums(memMat) #normalized membership matrix: replace raw flow value with fractional flow value.
memMat[is.na(memMat)]<-0 # replace NAs with 0s
memMat[17,11]<-1
memMat[147,12]<-1

Fmemb<-colSums(memMat) #To be used in mean and standard deviaton calculations

#Here is code for printing all session networks to a file
pdf("Cluster1.pdf")
plot(networkArray[[overlap$session.no[overlap$group==1][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][1],sub=memMat[which(memMat[,1]!=0),1][1])
plot(networkArray[[overlap$session.no[overlap$group==1][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][2],sub=memMat[which(memMat[,1]!=0),1][2])
plot(networkArray[[overlap$session.no[overlap$group==1][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][3],sub=memMat[which(memMat[,1]!=0),1][3])
plot(networkArray[[overlap$session.no[overlap$group==1][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][4],sub=memMat[which(memMat[,1]!=0),1][4])
plot(networkArray[[overlap$session.no[overlap$group==1][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][5],sub=memMat[which(memMat[,1]!=0),1][5])
plot(networkArray[[overlap$session.no[overlap$group==1][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][6],sub=memMat[which(memMat[,1]!=0),1][6])
plot(networkArray[[overlap$session.no[overlap$group==1][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][7],sub=memMat[which(memMat[,1]!=0),1][7])
plot(networkArray[[overlap$session.no[overlap$group==1][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][8],sub=memMat[which(memMat[,1]!=0),1][8])
plot(networkArray[[overlap$session.no[overlap$group==1][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][9],sub=memMat[which(memMat[,1]!=0),1][9])
plot(networkArray[[overlap$session.no[overlap$group==1][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][10],sub=memMat[which(memMat[,1]!=0),1][10])
plot(networkArray[[overlap$session.no[overlap$group==1][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][11],sub=memMat[which(memMat[,1]!=0),1][11])
plot(networkArray[[overlap$session.no[overlap$group==1][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][12],sub=memMat[which(memMat[,1]!=0),1][12])
plot(networkArray[[overlap$session.no[overlap$group==1][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][13],sub=memMat[which(memMat[,1]!=0),1][13])
plot(networkArray[[overlap$session.no[overlap$group==1][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][14],sub=memMat[which(memMat[,1]!=0),1][14])
plot(networkArray[[overlap$session.no[overlap$group==1][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][15],sub=memMat[which(memMat[,1]!=0),1][15])
plot(networkArray[[overlap$session.no[overlap$group==1][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][16],sub=memMat[which(memMat[,1]!=0),1][16])
plot(networkArray[[overlap$session.no[overlap$group==1][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][17],sub=memMat[which(memMat[,1]!=0),1][17])
plot(networkArray[[overlap$session.no[overlap$group==1][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][18],sub=memMat[which(memMat[,1]!=0),1][18])
plot(networkArray[[overlap$session.no[overlap$group==1][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][19],sub=memMat[which(memMat[,1]!=0),1][19])
plot(networkArray[[overlap$session.no[overlap$group==1][20]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][20],sub=memMat[which(memMat[,1]!=0),1][20])
plot(networkArray[[overlap$session.no[overlap$group==1][21]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][21],sub=memMat[which(memMat[,1]!=0),1][21])
plot(networkArray[[overlap$session.no[overlap$group==1][22]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][22],sub=memMat[which(memMat[,1]!=0),1][22])
plot(networkArray[[overlap$session.no[overlap$group==1][23]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][23],sub=memMat[which(memMat[,1]!=0),1][23])
plot(networkArray[[overlap$session.no[overlap$group==1][24]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][24],sub=memMat[which(memMat[,1]!=0),1][24])
plot(networkArray[[overlap$session.no[overlap$group==1][25]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][25],sub=memMat[which(memMat[,1]!=0),1][25])
plot(networkArray[[overlap$session.no[overlap$group==1][26]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][26],sub=memMat[which(memMat[,1]!=0),1][26])
plot(networkArray[[overlap$session.no[overlap$group==1][27]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][27],sub=memMat[which(memMat[,1]!=0),1][27])
plot(networkArray[[overlap$session.no[overlap$group==1][28]]],vertex.label=NA, main=overlap$session.no[overlap$group==1][28],sub=memMat[which(memMat[,1]!=0),1][28])

dev.off()

pdf("Cluster2.pdf")
plot(networkArray[[overlap$session.no[overlap$group==2][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][1],sub=memMat[which(memMat[,2]!=0),2][1])
plot(networkArray[[overlap$session.no[overlap$group==2][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][2],sub=memMat[which(memMat[,2]!=0),2][2])
plot(networkArray[[overlap$session.no[overlap$group==2][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][3],sub=memMat[which(memMat[,2]!=0),2][3])
plot(networkArray[[overlap$session.no[overlap$group==2][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][4],sub=memMat[which(memMat[,2]!=0),2][4])
plot(networkArray[[overlap$session.no[overlap$group==2][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][5],sub=memMat[which(memMat[,2]!=0),2][5])
plot(networkArray[[overlap$session.no[overlap$group==2][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][6],sub=memMat[which(memMat[,2]!=0),2][6])
plot(networkArray[[overlap$session.no[overlap$group==2][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][7],sub=memMat[which(memMat[,2]!=0),2][7])
plot(networkArray[[overlap$session.no[overlap$group==2][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][8],sub=memMat[which(memMat[,2]!=0),2][8])
plot(networkArray[[overlap$session.no[overlap$group==2][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][9],sub=memMat[which(memMat[,2]!=0),2][9])
plot(networkArray[[overlap$session.no[overlap$group==2][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][10],sub=memMat[which(memMat[,2]!=0),2][10])
plot(networkArray[[overlap$session.no[overlap$group==2][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][11],sub=memMat[which(memMat[,2]!=0),2][11])
plot(networkArray[[overlap$session.no[overlap$group==2][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][12],sub=memMat[which(memMat[,2]!=0),2][12])
plot(networkArray[[overlap$session.no[overlap$group==2][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][13],sub=memMat[which(memMat[,2]!=0),2][13])
plot(networkArray[[overlap$session.no[overlap$group==2][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][14],sub=memMat[which(memMat[,2]!=0),2][14])
plot(networkArray[[overlap$session.no[overlap$group==2][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][15],sub=memMat[which(memMat[,2]!=0),2][15])
plot(networkArray[[overlap$session.no[overlap$group==2][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][16],sub=memMat[which(memMat[,2]!=0),2][16])
plot(networkArray[[overlap$session.no[overlap$group==2][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][17],sub=memMat[which(memMat[,2]!=0),2][17])
plot(networkArray[[overlap$session.no[overlap$group==2][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][18],sub=memMat[which(memMat[,2]!=0),2][18])
plot(networkArray[[overlap$session.no[overlap$group==2][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][19],sub=memMat[which(memMat[,2]!=0),2][19])
plot(networkArray[[overlap$session.no[overlap$group==2][20]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][20],sub=memMat[which(memMat[,2]!=0),2][20])
plot(networkArray[[overlap$session.no[overlap$group==2][21]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][21],sub=memMat[which(memMat[,2]!=0),2][21])
plot(networkArray[[overlap$session.no[overlap$group==2][22]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][22],sub=memMat[which(memMat[,2]!=0),2][22])
plot(networkArray[[overlap$session.no[overlap$group==2][23]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][23],sub=memMat[which(memMat[,2]!=0),2][23])
plot(networkArray[[overlap$session.no[overlap$group==2][24]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][24],sub=memMat[which(memMat[,2]!=0),2][24])
plot(networkArray[[overlap$session.no[overlap$group==2][25]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][25],sub=memMat[which(memMat[,2]!=0),2][25])
plot(networkArray[[overlap$session.no[overlap$group==2][26]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][26],sub=memMat[which(memMat[,2]!=0),2][26])
plot(networkArray[[overlap$session.no[overlap$group==2][27]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][27],sub=memMat[which(memMat[,2]!=0),2][27])
plot(networkArray[[overlap$session.no[overlap$group==2][28]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][28],sub=memMat[which(memMat[,2]!=0),2][28])
plot(networkArray[[overlap$session.no[overlap$group==2][29]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][29],sub=memMat[which(memMat[,2]!=0),2][29])
plot(networkArray[[overlap$session.no[overlap$group==2][30]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][30],sub=memMat[which(memMat[,2]!=0),2][30])
plot(networkArray[[overlap$session.no[overlap$group==2][31]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][31],sub=memMat[which(memMat[,2]!=0),2][31])
plot(networkArray[[overlap$session.no[overlap$group==2][32]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][32],sub=memMat[which(memMat[,2]!=0),2][32])
plot(networkArray[[overlap$session.no[overlap$group==2][33]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][33],sub=memMat[which(memMat[,2]!=0),2][33])
plot(networkArray[[overlap$session.no[overlap$group==2][34]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][34],sub=memMat[which(memMat[,2]!=0),2][34])
plot(networkArray[[overlap$session.no[overlap$group==2][35]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][35],sub=memMat[which(memMat[,2]!=0),2][35])
plot(networkArray[[overlap$session.no[overlap$group==2][36]]],vertex.label=NA, main=overlap$session.no[overlap$group==2][36],sub=memMat[which(memMat[,2]!=0),2][36])

dev.off()


pdf("Cluster3.pdf")
plot(networkArray[[overlap$session.no[overlap$group==3][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][1],sub=memMat[which(memMat[,3]!=0),3][1])
plot(networkArray[[overlap$session.no[overlap$group==3][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][2],sub=memMat[which(memMat[,3]!=0),3][2])
plot(networkArray[[overlap$session.no[overlap$group==3][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][3],sub=memMat[which(memMat[,3]!=0),3][3])
plot(networkArray[[overlap$session.no[overlap$group==3][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][4],sub=memMat[which(memMat[,3]!=0),3][4])
plot(networkArray[[overlap$session.no[overlap$group==3][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][5],sub=memMat[which(memMat[,3]!=0),3][5])
plot(networkArray[[overlap$session.no[overlap$group==3][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][6],sub=memMat[which(memMat[,3]!=0),3][6])
plot(networkArray[[overlap$session.no[overlap$group==3][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][7],sub=memMat[which(memMat[,3]!=0),3][7])
plot(networkArray[[overlap$session.no[overlap$group==3][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][8],sub=memMat[which(memMat[,3]!=0),3][8])
plot(networkArray[[overlap$session.no[overlap$group==3][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][9],sub=memMat[which(memMat[,3]!=0),3][9])
plot(networkArray[[overlap$session.no[overlap$group==3][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][10],sub=memMat[which(memMat[,3]!=0),3][10])
plot(networkArray[[overlap$session.no[overlap$group==3][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][11],sub=memMat[which(memMat[,3]!=0),3][11])
plot(networkArray[[overlap$session.no[overlap$group==3][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][12],sub=memMat[which(memMat[,3]!=0),3][12])
plot(networkArray[[overlap$session.no[overlap$group==3][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][13],sub=memMat[which(memMat[,3]!=0),3][13])
plot(networkArray[[overlap$session.no[overlap$group==3][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][14],sub=memMat[which(memMat[,3]!=0),3][14])
plot(networkArray[[overlap$session.no[overlap$group==3][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][15],sub=memMat[which(memMat[,3]!=0),3][15])
plot(networkArray[[overlap$session.no[overlap$group==3][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][16],sub=memMat[which(memMat[,3]!=0),3][16])
plot(networkArray[[overlap$session.no[overlap$group==3][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][17],sub=memMat[which(memMat[,3]!=0),3][17])
plot(networkArray[[overlap$session.no[overlap$group==3][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][18],sub=memMat[which(memMat[,3]!=0),3][18])
plot(networkArray[[overlap$session.no[overlap$group==3][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][19],sub=memMat[which(memMat[,3]!=0),3][19])
plot(networkArray[[overlap$session.no[overlap$group==3][20]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][20],sub=memMat[which(memMat[,3]!=0),3][20])
plot(networkArray[[overlap$session.no[overlap$group==3][21]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][21],sub=memMat[which(memMat[,3]!=0),3][21])
plot(networkArray[[overlap$session.no[overlap$group==3][22]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][22],sub=memMat[which(memMat[,3]!=0),3][22])
plot(networkArray[[overlap$session.no[overlap$group==3][23]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][23],sub=memMat[which(memMat[,3]!=0),3][23])
plot(networkArray[[overlap$session.no[overlap$group==3][24]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][24],sub=memMat[which(memMat[,3]!=0),3][24])
plot(networkArray[[overlap$session.no[overlap$group==3][25]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][25],sub=memMat[which(memMat[,3]!=0),3][25])
plot(networkArray[[overlap$session.no[overlap$group==3][26]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][26],sub=memMat[which(memMat[,3]!=0),3][26])
plot(networkArray[[overlap$session.no[overlap$group==3][27]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][27],sub=memMat[which(memMat[,3]!=0),3][27])
plot(networkArray[[overlap$session.no[overlap$group==3][28]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][28],sub=memMat[which(memMat[,3]!=0),3][28])
plot(networkArray[[overlap$session.no[overlap$group==3][29]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][29],sub=memMat[which(memMat[,3]!=0),3][29])
plot(networkArray[[overlap$session.no[overlap$group==3][30]]],vertex.label=NA, main=overlap$session.no[overlap$group==3][30],sub=memMat[which(memMat[,3]!=0),3][30])

dev.off()

pdf("Cluster4.pdf")
plot(networkArray[[overlap$session.no[overlap$group==4][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][1],sub=memMat[which(memMat[,4]!=0),4][1])
plot(networkArray[[overlap$session.no[overlap$group==4][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][2],sub=memMat[which(memMat[,4]!=0),4][2])
plot(networkArray[[overlap$session.no[overlap$group==4][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][3],sub=memMat[which(memMat[,4]!=0),4][3])
plot(networkArray[[overlap$session.no[overlap$group==4][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][4],sub=memMat[which(memMat[,4]!=0),4][4])
plot(networkArray[[overlap$session.no[overlap$group==4][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][5],sub=memMat[which(memMat[,4]!=0),4][5])
plot(networkArray[[overlap$session.no[overlap$group==4][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][6],sub=memMat[which(memMat[,4]!=0),4][6])
plot(networkArray[[overlap$session.no[overlap$group==4][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][7],sub=memMat[which(memMat[,4]!=0),4][7])
plot(networkArray[[overlap$session.no[overlap$group==4][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][8],sub=memMat[which(memMat[,4]!=0),4][8])
plot(networkArray[[overlap$session.no[overlap$group==4][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][9],sub=memMat[which(memMat[,4]!=0),4][9])
plot(networkArray[[overlap$session.no[overlap$group==4][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][10],sub=memMat[which(memMat[,4]!=0),4][10])
plot(networkArray[[overlap$session.no[overlap$group==4][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][11],sub=memMat[which(memMat[,4]!=0),4][11])
plot(networkArray[[overlap$session.no[overlap$group==4][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][12],sub=memMat[which(memMat[,4]!=0),4][12])
plot(networkArray[[overlap$session.no[overlap$group==4][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][13],sub=memMat[which(memMat[,4]!=0),4][13])
plot(networkArray[[overlap$session.no[overlap$group==4][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][14],sub=memMat[which(memMat[,4]!=0),4][14])
plot(networkArray[[overlap$session.no[overlap$group==4][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][15],sub=memMat[which(memMat[,4]!=0),4][15])
plot(networkArray[[overlap$session.no[overlap$group==4][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][16],sub=memMat[which(memMat[,4]!=0),4][16])
plot(networkArray[[overlap$session.no[overlap$group==4][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][17],sub=memMat[which(memMat[,4]!=0),4][17])
plot(networkArray[[overlap$session.no[overlap$group==4][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][18],sub=memMat[which(memMat[,4]!=0),4][18])
plot(networkArray[[overlap$session.no[overlap$group==4][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][19],sub=memMat[which(memMat[,4]!=0),4][19])
plot(networkArray[[overlap$session.no[overlap$group==4][20]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][20],sub=memMat[which(memMat[,4]!=0),4][20])
plot(networkArray[[overlap$session.no[overlap$group==4][21]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][21],sub=memMat[which(memMat[,4]!=0),4][21])
plot(networkArray[[overlap$session.no[overlap$group==4][22]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][22],sub=memMat[which(memMat[,4]!=0),4][22])
plot(networkArray[[overlap$session.no[overlap$group==4][23]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][23],sub=memMat[which(memMat[,4]!=0),4][23])
plot(networkArray[[overlap$session.no[overlap$group==4][24]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][24],sub=memMat[which(memMat[,4]!=0),4][24])
plot(networkArray[[overlap$session.no[overlap$group==4][25]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][25],sub=memMat[which(memMat[,4]!=0),4][25])
plot(networkArray[[overlap$session.no[overlap$group==4][26]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][26],sub=memMat[which(memMat[,4]!=0),4][26])
plot(networkArray[[overlap$session.no[overlap$group==4][27]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][27],sub=memMat[which(memMat[,4]!=0),4][27])
plot(networkArray[[overlap$session.no[overlap$group==4][28]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][28],sub=memMat[which(memMat[,4]!=0),4][28])
plot(networkArray[[overlap$session.no[overlap$group==4][29]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][29],sub=memMat[which(memMat[,4]!=0),4][29])
plot(networkArray[[overlap$session.no[overlap$group==4][30]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][30],sub=memMat[which(memMat[,4]!=0),4][30])
plot(networkArray[[overlap$session.no[overlap$group==4][31]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][31],sub=memMat[which(memMat[,4]!=0),4][31])
plot(networkArray[[overlap$session.no[overlap$group==4][32]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][32],sub=memMat[which(memMat[,4]!=0),4][32])
plot(networkArray[[overlap$session.no[overlap$group==4][33]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][33],sub=memMat[which(memMat[,4]!=0),4][33])
plot(networkArray[[overlap$session.no[overlap$group==4][34]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][34],sub=memMat[which(memMat[,4]!=0),4][34])
plot(networkArray[[overlap$session.no[overlap$group==4][35]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][35],sub=memMat[which(memMat[,4]!=0),4][35])
plot(networkArray[[overlap$session.no[overlap$group==4][36]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][36],sub=memMat[which(memMat[,4]!=0),4][36])
plot(networkArray[[overlap$session.no[overlap$group==4][37]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][37],sub=memMat[which(memMat[,4]!=0),4][37])
plot(networkArray[[overlap$session.no[overlap$group==4][38]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][38],sub=memMat[which(memMat[,4]!=0),4][38])
plot(networkArray[[overlap$session.no[overlap$group==4][39]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][39],sub=memMat[which(memMat[,4]!=0),4][39])
plot(networkArray[[overlap$session.no[overlap$group==4][40]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][40],sub=memMat[which(memMat[,4]!=0),4][40])
plot(networkArray[[overlap$session.no[overlap$group==4][41]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][41],sub=memMat[which(memMat[,4]!=0),4][41])
plot(networkArray[[overlap$session.no[overlap$group==4][42]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][42],sub=memMat[which(memMat[,4]!=0),4][42])
plot(networkArray[[overlap$session.no[overlap$group==4][43]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][43],sub=memMat[which(memMat[,4]!=0),4][43])
plot(networkArray[[overlap$session.no[overlap$group==4][44]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][44],sub=memMat[which(memMat[,4]!=0),4][44])
plot(networkArray[[overlap$session.no[overlap$group==4][45]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][45],sub=memMat[which(memMat[,4]!=0),4][45])
plot(networkArray[[overlap$session.no[overlap$group==4][46]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][46],sub=memMat[which(memMat[,4]!=0),4][46])
plot(networkArray[[overlap$session.no[overlap$group==4][47]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][47],sub=memMat[which(memMat[,4]!=0),4][47])
plot(networkArray[[overlap$session.no[overlap$group==4][48]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][48],sub=memMat[which(memMat[,4]!=0),4][48])
plot(networkArray[[overlap$session.no[overlap$group==4][49]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][49],sub=memMat[which(memMat[,4]!=0),4][49])
plot(networkArray[[overlap$session.no[overlap$group==4][50]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][50],sub=memMat[which(memMat[,4]!=0),4][50])
plot(networkArray[[overlap$session.no[overlap$group==4][51]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][51],sub=memMat[which(memMat[,4]!=0),4][51])
plot(networkArray[[overlap$session.no[overlap$group==4][52]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][52],sub=memMat[which(memMat[,4]!=0),4][52])
plot(networkArray[[overlap$session.no[overlap$group==4][53]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][53],sub=memMat[which(memMat[,4]!=0),4][53])
plot(networkArray[[overlap$session.no[overlap$group==4][54]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][54],sub=memMat[which(memMat[,4]!=0),4][54])
plot(networkArray[[overlap$session.no[overlap$group==4][55]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][55],sub=memMat[which(memMat[,4]!=0),4][55])
plot(networkArray[[overlap$session.no[overlap$group==4][56]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][56],sub=memMat[which(memMat[,4]!=0),4][56])
plot(networkArray[[overlap$session.no[overlap$group==4][57]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][57],sub=memMat[which(memMat[,4]!=0),4][57])
plot(networkArray[[overlap$session.no[overlap$group==4][58]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][58],sub=memMat[which(memMat[,4]!=0),4][58])
plot(networkArray[[overlap$session.no[overlap$group==4][59]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][59],sub=memMat[which(memMat[,4]!=0),4][59])
plot(networkArray[[overlap$session.no[overlap$group==4][60]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][60],sub=memMat[which(memMat[,4]!=0),4][60])
plot(networkArray[[overlap$session.no[overlap$group==4][61]]],vertex.label=NA, main=overlap$session.no[overlap$group==4][61],sub=memMat[which(memMat[,4]!=0),4][61])

dev.off()

pdf("Cluster5.pdf")
plot(networkArray[[overlap$session.no[overlap$group==5][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][1],sub=memMat[which(memMat[,5]!=0),5][1])
plot(networkArray[[overlap$session.no[overlap$group==5][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][2],sub=memMat[which(memMat[,5]!=0),5][2])
plot(networkArray[[overlap$session.no[overlap$group==5][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][3],sub=memMat[which(memMat[,5]!=0),5][3])
plot(networkArray[[overlap$session.no[overlap$group==5][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][4],sub=memMat[which(memMat[,5]!=0),5][4])
plot(networkArray[[overlap$session.no[overlap$group==5][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][5],sub=memMat[which(memMat[,5]!=0),5][5])
plot(networkArray[[overlap$session.no[overlap$group==5][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][6],sub=memMat[which(memMat[,5]!=0),5][6])
plot(networkArray[[overlap$session.no[overlap$group==5][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][7],sub=memMat[which(memMat[,5]!=0),5][7])
plot(networkArray[[overlap$session.no[overlap$group==5][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][8],sub=memMat[which(memMat[,5]!=0),5][8])
plot(networkArray[[overlap$session.no[overlap$group==5][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][9],sub=memMat[which(memMat[,5]!=0),5][9])
plot(networkArray[[overlap$session.no[overlap$group==5][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][10],sub=memMat[which(memMat[,5]!=0),5][10])
plot(networkArray[[overlap$session.no[overlap$group==5][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][11],sub=memMat[which(memMat[,5]!=0),5][11])
plot(networkArray[[overlap$session.no[overlap$group==5][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][12],sub=memMat[which(memMat[,5]!=0),5][12])
plot(networkArray[[overlap$session.no[overlap$group==5][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][13],sub=memMat[which(memMat[,5]!=0),5][13])
plot(networkArray[[overlap$session.no[overlap$group==5][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][14],sub=memMat[which(memMat[,5]!=0),5][14])
plot(networkArray[[overlap$session.no[overlap$group==5][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][15],sub=memMat[which(memMat[,5]!=0),5][15])
plot(networkArray[[overlap$session.no[overlap$group==5][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][16],sub=memMat[which(memMat[,5]!=0),5][16])
plot(networkArray[[overlap$session.no[overlap$group==5][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][17],sub=memMat[which(memMat[,5]!=0),5][17])
plot(networkArray[[overlap$session.no[overlap$group==5][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][18],sub=memMat[which(memMat[,5]!=0),5][18])
plot(networkArray[[overlap$session.no[overlap$group==5][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==5][19],sub=memMat[which(memMat[,5]!=0),5][19])
dev.off()

pdf("Cluster6.pdf")
plot(networkArray[[overlap$session.no[overlap$group==6][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][1],sub=memMat[which(memMat[,6]!=0),6][1])
plot(networkArray[[overlap$session.no[overlap$group==6][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][2],sub=memMat[which(memMat[,6]!=0),6][2])
plot(networkArray[[overlap$session.no[overlap$group==6][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][3],sub=memMat[which(memMat[,6]!=0),6][3])
plot(networkArray[[overlap$session.no[overlap$group==6][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][4],sub=memMat[which(memMat[,6]!=0),6][4])
plot(networkArray[[overlap$session.no[overlap$group==6][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][5],sub=memMat[which(memMat[,6]!=0),6][5])
plot(networkArray[[overlap$session.no[overlap$group==6][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][6],sub=memMat[which(memMat[,6]!=0),6][6])
plot(networkArray[[overlap$session.no[overlap$group==6][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][7],sub=memMat[which(memMat[,6]!=0),6][7])
plot(networkArray[[overlap$session.no[overlap$group==6][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][8],sub=memMat[which(memMat[,6]!=0),6][8])
plot(networkArray[[overlap$session.no[overlap$group==6][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][9],sub=memMat[which(memMat[,6]!=0),6][9])
plot(networkArray[[overlap$session.no[overlap$group==6][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][10],sub=memMat[which(memMat[,6]!=0),6][10])
plot(networkArray[[overlap$session.no[overlap$group==6][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][11],sub=memMat[which(memMat[,6]!=0),6][11])
plot(networkArray[[overlap$session.no[overlap$group==6][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][12],sub=memMat[which(memMat[,6]!=0),6][12])
plot(networkArray[[overlap$session.no[overlap$group==6][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][13],sub=memMat[which(memMat[,6]!=0),6][13])
plot(networkArray[[overlap$session.no[overlap$group==6][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][14],sub=memMat[which(memMat[,6]!=0),6][14])
plot(networkArray[[overlap$session.no[overlap$group==6][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][15],sub=memMat[which(memMat[,6]!=0),6][15])
plot(networkArray[[overlap$session.no[overlap$group==6][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][16],sub=memMat[which(memMat[,6]!=0),6][16])
plot(networkArray[[overlap$session.no[overlap$group==6][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][17],sub=memMat[which(memMat[,6]!=0),6][17])
plot(networkArray[[overlap$session.no[overlap$group==6][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][18],sub=memMat[which(memMat[,6]!=0),6][18])
plot(networkArray[[overlap$session.no[overlap$group==6][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][19],sub=memMat[which(memMat[,6]!=0),6][19])
plot(networkArray[[overlap$session.no[overlap$group==6][20]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][20],sub=memMat[which(memMat[,6]!=0),6][20])
plot(networkArray[[overlap$session.no[overlap$group==6][21]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][21],sub=memMat[which(memMat[,6]!=0),6][21])
plot(networkArray[[overlap$session.no[overlap$group==6][22]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][22],sub=memMat[which(memMat[,6]!=0),6][22])
plot(networkArray[[overlap$session.no[overlap$group==6][23]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][23],sub=memMat[which(memMat[,6]!=0),6][23])
plot(networkArray[[overlap$session.no[overlap$group==6][24]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][24],sub=memMat[which(memMat[,6]!=0),6][24])
plot(networkArray[[overlap$session.no[overlap$group==6][25]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][25],sub=memMat[which(memMat[,6]!=0),6][25])
plot(networkArray[[overlap$session.no[overlap$group==6][26]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][26],sub=memMat[which(memMat[,6]!=0),6][26])
plot(networkArray[[overlap$session.no[overlap$group==6][27]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][27],sub=memMat[which(memMat[,6]!=0),6][27])
plot(networkArray[[overlap$session.no[overlap$group==6][28]]],vertex.label=NA, main=overlap$session.no[overlap$group==6][28],sub=memMat[which(memMat[,6]!=0),6][28])

dev.off()

pdf("Cluster7.pdf")
plot(networkArray[[overlap$session.no[overlap$group==7][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][1],sub=memMat[which(memMat[,7]!=0),7][1])
plot(networkArray[[overlap$session.no[overlap$group==7][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][2],sub=memMat[which(memMat[,7]!=0),7][2])
plot(networkArray[[overlap$session.no[overlap$group==7][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][3],sub=memMat[which(memMat[,7]!=0),7][3])
plot(networkArray[[overlap$session.no[overlap$group==7][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][4],sub=memMat[which(memMat[,7]!=0),7][4])
plot(networkArray[[overlap$session.no[overlap$group==7][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][5],sub=memMat[which(memMat[,7]!=0),7][5])
plot(networkArray[[overlap$session.no[overlap$group==7][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][6],sub=memMat[which(memMat[,7]!=0),7][6])
plot(networkArray[[overlap$session.no[overlap$group==7][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][7],sub=memMat[which(memMat[,7]!=0),7][7])
plot(networkArray[[overlap$session.no[overlap$group==7][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][8],sub=memMat[which(memMat[,7]!=0),7][8])
plot(networkArray[[overlap$session.no[overlap$group==7][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][9],sub=memMat[which(memMat[,7]!=0),7][9])
plot(networkArray[[overlap$session.no[overlap$group==7][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][10],sub=memMat[which(memMat[,7]!=0),7][10])
plot(networkArray[[overlap$session.no[overlap$group==7][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][11],sub=memMat[which(memMat[,7]!=0),7][11])
plot(networkArray[[overlap$session.no[overlap$group==7][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][12],sub=memMat[which(memMat[,7]!=0),7][12])
plot(networkArray[[overlap$session.no[overlap$group==7][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==7][13],sub=memMat[which(memMat[,7]!=0),7][13])
dev.off()

pdf("Cluster8.pdf")
plot(networkArray[[overlap$session.no[overlap$group==8][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][1],sub=memMat[which(memMat[,8]!=0),8][1])
plot(networkArray[[overlap$session.no[overlap$group==8][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][2],sub=memMat[which(memMat[,8]!=0),8][2])
plot(networkArray[[overlap$session.no[overlap$group==8][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][3],sub=memMat[which(memMat[,8]!=0),8][3])
plot(networkArray[[overlap$session.no[overlap$group==8][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][4],sub=memMat[which(memMat[,8]!=0),8][4])
plot(networkArray[[overlap$session.no[overlap$group==8][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][5],sub=memMat[which(memMat[,8]!=0),8][5])
plot(networkArray[[overlap$session.no[overlap$group==8][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][6],sub=memMat[which(memMat[,8]!=0),8][6])
plot(networkArray[[overlap$session.no[overlap$group==8][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][7],sub=memMat[which(memMat[,8]!=0),8][7])
plot(networkArray[[overlap$session.no[overlap$group==8][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][8],sub=memMat[which(memMat[,8]!=0),8][8])
plot(networkArray[[overlap$session.no[overlap$group==8][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][9],sub=memMat[which(memMat[,8]!=0),8][9])
plot(networkArray[[overlap$session.no[overlap$group==8][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][10],sub=memMat[which(memMat[,8]!=0),8][10])
plot(networkArray[[overlap$session.no[overlap$group==8][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][11],sub=memMat[which(memMat[,8]!=0),8][11])
plot(networkArray[[overlap$session.no[overlap$group==8][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][12],sub=memMat[which(memMat[,8]!=0),8][12])
plot(networkArray[[overlap$session.no[overlap$group==8][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][13],sub=memMat[which(memMat[,8]!=0),8][13])
plot(networkArray[[overlap$session.no[overlap$group==8][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][14],sub=memMat[which(memMat[,8]!=0),8][14])
plot(networkArray[[overlap$session.no[overlap$group==8][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][15],sub=memMat[which(memMat[,8]!=0),8][15])
plot(networkArray[[overlap$session.no[overlap$group==8][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][16],sub=memMat[which(memMat[,8]!=0),8][16])
plot(networkArray[[overlap$session.no[overlap$group==8][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][17],sub=memMat[which(memMat[,8]!=0),8][17])
plot(networkArray[[overlap$session.no[overlap$group==8][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][18],sub=memMat[which(memMat[,8]!=0),8][18])
plot(networkArray[[overlap$session.no[overlap$group==8][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][19],sub=memMat[which(memMat[,8]!=0),8][19])
plot(networkArray[[overlap$session.no[overlap$group==8][20]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][20],sub=memMat[which(memMat[,8]!=0),8][20])
plot(networkArray[[overlap$session.no[overlap$group==8][21]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][21],sub=memMat[which(memMat[,8]!=0),8][21])
plot(networkArray[[overlap$session.no[overlap$group==8][22]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][22],sub=memMat[which(memMat[,8]!=0),8][22])
plot(networkArray[[overlap$session.no[overlap$group==8][23]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][23],sub=memMat[which(memMat[,8]!=0),8][23])
plot(networkArray[[overlap$session.no[overlap$group==8][24]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][24],sub=memMat[which(memMat[,8]!=0),8][24])
plot(networkArray[[overlap$session.no[overlap$group==8][25]]],vertex.label=NA, main=overlap$session.no[overlap$group==8][25],sub=memMat[which(memMat[,8]!=0),8][25])
dev.off()

pdf("Cluster9.pdf")
plot(networkArray[[overlap$session.no[overlap$group==9][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][1],sub=memMat[which(memMat[,9]!=0),9][1])
plot(networkArray[[overlap$session.no[overlap$group==9][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][2],sub=memMat[which(memMat[,9]!=0),9][2])
plot(networkArray[[overlap$session.no[overlap$group==9][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][3],sub=memMat[which(memMat[,9]!=0),9][3])
plot(networkArray[[overlap$session.no[overlap$group==9][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][4],sub=memMat[which(memMat[,9]!=0),9][4])
plot(networkArray[[overlap$session.no[overlap$group==9][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][5],sub=memMat[which(memMat[,9]!=0),9][5])
plot(networkArray[[overlap$session.no[overlap$group==9][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][6],sub=memMat[which(memMat[,9]!=0),9][6])
plot(networkArray[[overlap$session.no[overlap$group==9][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][7],sub=memMat[which(memMat[,9]!=0),9][7])
plot(networkArray[[overlap$session.no[overlap$group==9][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][8],sub=memMat[which(memMat[,9]!=0),9][8])
plot(networkArray[[overlap$session.no[overlap$group==9][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][9],sub=memMat[which(memMat[,9]!=0),9][9])
plot(networkArray[[overlap$session.no[overlap$group==9][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][10],sub=memMat[which(memMat[,9]!=0),9][10])
plot(networkArray[[overlap$session.no[overlap$group==9][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][11],sub=memMat[which(memMat[,9]!=0),9][11])
plot(networkArray[[overlap$session.no[overlap$group==9][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][12],sub=memMat[which(memMat[,9]!=0),9][12])
plot(networkArray[[overlap$session.no[overlap$group==9][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][13],sub=memMat[which(memMat[,9]!=0),9][13])
plot(networkArray[[overlap$session.no[overlap$group==9][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][14],sub=memMat[which(memMat[,9]!=0),9][14])
plot(networkArray[[overlap$session.no[overlap$group==9][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][15],sub=memMat[which(memMat[,9]!=0),9][15])
plot(networkArray[[overlap$session.no[overlap$group==9][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][16],sub=memMat[which(memMat[,9]!=0),9][16])
plot(networkArray[[overlap$session.no[overlap$group==9][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][17],sub=memMat[which(memMat[,9]!=0),9][17])
plot(networkArray[[overlap$session.no[overlap$group==9][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][18],sub=memMat[which(memMat[,9]!=0),9][18])
plot(networkArray[[overlap$session.no[overlap$group==9][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][19],sub=memMat[which(memMat[,9]!=0),9][19])
plot(networkArray[[overlap$session.no[overlap$group==9][20]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][20],sub=memMat[which(memMat[,9]!=0),9][20])
plot(networkArray[[overlap$session.no[overlap$group==9][21]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][21],sub=memMat[which(memMat[,9]!=0),9][21])
plot(networkArray[[overlap$session.no[overlap$group==9][22]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][22],sub=memMat[which(memMat[,9]!=0),9][22])
plot(networkArray[[overlap$session.no[overlap$group==9][23]]],vertex.label=NA, main=overlap$session.no[overlap$group==9][23],sub=memMat[which(memMat[,9]!=0),9][23])
dev.off()

pdf("Cluster10.pdf")
plot(networkArray[[overlap$session.no[overlap$group==10][1]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][1],sub=memMat[which(memMat[,10]!=0),10][1])
plot(networkArray[[overlap$session.no[overlap$group==10][2]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][2],sub=memMat[which(memMat[,10]!=0),10][2])
plot(networkArray[[overlap$session.no[overlap$group==10][3]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][3],sub=memMat[which(memMat[,10]!=0),10][3])
plot(networkArray[[overlap$session.no[overlap$group==10][4]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][4],sub=memMat[which(memMat[,10]!=0),10][4])
plot(networkArray[[overlap$session.no[overlap$group==10][5]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][5],sub=memMat[which(memMat[,10]!=0),10][5])
plot(networkArray[[overlap$session.no[overlap$group==10][6]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][6],sub=memMat[which(memMat[,10]!=0),10][6])
plot(networkArray[[overlap$session.no[overlap$group==10][7]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][7],sub=memMat[which(memMat[,10]!=0),10][7])
plot(networkArray[[overlap$session.no[overlap$group==10][8]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][8],sub=memMat[which(memMat[,10]!=0),10][8])
plot(networkArray[[overlap$session.no[overlap$group==10][9]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][9],sub=memMat[which(memMat[,10]!=0),10][9])
plot(networkArray[[overlap$session.no[overlap$group==10][10]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][10],sub=memMat[which(memMat[,10]!=0),10][10])
plot(networkArray[[overlap$session.no[overlap$group==10][11]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][11],sub=memMat[which(memMat[,10]!=0),10][11])
plot(networkArray[[overlap$session.no[overlap$group==10][12]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][12],sub=memMat[which(memMat[,10]!=0),10][12])
plot(networkArray[[overlap$session.no[overlap$group==10][13]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][13],sub=memMat[which(memMat[,10]!=0),10][13])
plot(networkArray[[overlap$session.no[overlap$group==10][14]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][14],sub=memMat[which(memMat[,10]!=0),10][14])
plot(networkArray[[overlap$session.no[overlap$group==10][15]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][15],sub=memMat[which(memMat[,10]!=0),10][15])
plot(networkArray[[overlap$session.no[overlap$group==10][16]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][16],sub=memMat[which(memMat[,10]!=0),10][16])
plot(networkArray[[overlap$session.no[overlap$group==10][17]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][17],sub=memMat[which(memMat[,10]!=0),10][17])
plot(networkArray[[overlap$session.no[overlap$group==10][18]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][18],sub=memMat[which(memMat[,10]!=0),10][18])
plot(networkArray[[overlap$session.no[overlap$group==10][19]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][19],sub=memMat[which(memMat[,10]!=0),10][19])
plot(networkArray[[overlap$session.no[overlap$group==10][20]]],vertex.label=NA, main=overlap$session.no[overlap$group==10][20],sub=memMat[which(memMat[,10]!=0),10][20])
dev.off()